name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./Src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --no-build --verbosity normal
