name: .NET with CI Visibility

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
      DD_SITE: datad0g.com
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APPLICATION_KEY: ${{ secrets.DD_APPLICATION_KEY }}
      DD_ENV: ci
      DD_SERVICE: JSON.NET CI VISIBILITY

    defaults:
      run:
        working-directory: ./Src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install dd-trace
      run: dotnet tool update dd-trace -g --add-source ../

    - name: Build
      run: dotnet build

    - name: Test With ITR
      run: dd-trace ci run -- dotnet test --no-build --verbosity normal
